"""create opponent tables (opponent_sessions, opponent_case_files, opponent_llm_calls)

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 15:46:41.701026
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opponent_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('motion', sa.Text(), nullable=False),
    sa.Column('ai_side', sa.Enum('pro', 'con', name='debate_side'), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='opponent_difficulty'), nullable=False),
    sa.Column('language', sa.String(length=10), server_default='vi', nullable=False),
    sa.Column('status', sa.Enum('created', 'planning', 'ready', 'failed', name='opponent_session_status'), server_default='created', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opponent_case_files',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('llm_provider', sa.String(length=50), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['opponent_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opponent_case_files_session_id'), 'opponent_case_files', ['session_id'], unique=False)
    op.create_table('opponent_llm_calls',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.Enum('case_plan', name='llm_call_purpose'), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('llm_provider', sa.String(length=50), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['opponent_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opponent_llm_calls_session_id'), 'opponent_llm_calls', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opponent_llm_calls_session_id'), table_name='opponent_llm_calls')
    op.drop_table('opponent_llm_calls')
    op.drop_index(op.f('ix_opponent_case_files_session_id'), table_name='opponent_case_files')
    op.drop_table('opponent_case_files')
    op.drop_table('opponent_sessions')
    # ### end Alembic commands ###
    # Autogenerate khong tu xoa enum type cua Postgres -> xoa tay de upgrade lai khong loi "type already exists".
    for enum_name in ('llm_call_purpose', 'opponent_session_status', 'opponent_difficulty', 'debate_side'):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
